# Generated by Django 5.1.4 on 2024-12-14 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_fotografia_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fotografia',
            name='categoria',
            field=models.CharField(choices=[('Nebulosa', 'NEBULOSA'), ('ESTRELA', 'Estrela'), ('GALÁXIA', 'Galáxia'), ('Planeta', 'PLANETA')], default='', max_length=100),
        ),
    ]
